name: windows_single_instance
description: Forces a single instance of your Windows app
version: 0.1.0
homepage: https://github.com/Jon-Salmon/flutter_windows_single_instance

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  win32: ^2.5.1
  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WindowsSingleInstancePlugin
